services:
  - type: web
    name: super-converter-pdf-word
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: MAX_PDF_MB
        value: "25"
